apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: eventhubs-pubsub-subscription
spec:
  topic: dt-output
  route: /dt-output
  pubsubname: eventhubs-pubsub
  metadata:
    requireAllProperties: true
    rawPayload: false
scopes:
- orderprocessing
- checkout
- dapr-consumer